# Generated by Django 3.0.3 on 2020-03-04 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhoneName', models.CharField(max_length=40)),
                ('CnetURL', models.CharField(max_length=160)),
                ('WiredURL', models.CharField(max_length=160)),
                ('PCMagURL', models.CharField(max_length=160)),
                ('VergeURL', models.CharField(max_length=160)),
                ('DataAdded', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('PhoneID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CellCheck.Phone')),
                ('SiteID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CellCheck.Site')),
            ],
        ),
        migrations.CreateModel(
            name='ProList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pros', models.CharField(max_length=200)),
                ('PhoneID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CellCheck.Phone')),
                ('SiteID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CellCheck.Site')),
            ],
        ),
        migrations.CreateModel(
            name='ConList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cons', models.CharField(max_length=200)),
                ('PhoneID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CellCheck.Phone')),
                ('SiteID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CellCheck.Site')),
            ],
        ),
        migrations.CreateModel(
            name='CNETDetailedScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Design', models.PositiveSmallIntegerField()),
                ('Features', models.PositiveSmallIntegerField()),
                ('Performance', models.PositiveSmallIntegerField()),
                ('Camera', models.PositiveSmallIntegerField()),
                ('Battery', models.PositiveSmallIntegerField()),
                ('phoneID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CellCheck.Phone')),
            ],
        ),
    ]
