# Generated by Django 3.0.3 on 2020-03-04 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CellCheck', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='Name',
            new_name='SiteName',
        ),
    ]
