# Generated by Django 3.0.3 on 2020-03-04 20:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CellCheck', '0002_auto_20200304_0351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='DataAdded',
        ),
        migrations.AddField(
            model_name='phone',
            name='DateAdded',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
