# Generated by Django 3.0.3 on 2020-03-05 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CellCheck', '0003_auto_20200304_2031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cnetdetailedscore',
            old_name='phoneID',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='conlist',
            old_name='PhoneID',
            new_name='Phone',
        ),
        migrations.RenameField(
            model_name='conlist',
            old_name='SiteID',
            new_name='Site',
        ),
        migrations.RenameField(
            model_name='prolist',
            old_name='PhoneID',
            new_name='Phone',
        ),
        migrations.RenameField(
            model_name='prolist',
            old_name='SiteID',
            new_name='Site',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='PhoneID',
            new_name='Phone',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='SiteID',
            new_name='Site',
        ),
    ]
